### ISSUE TITLE
Página de dashboard

### ISSUE THREAD

**Issue by juanbelieni** [juanbelieni/romme-net#1]
Página com informações gerais sobre as ocorrências registradas recentemente,

É interessante pesquisar como se organiza um dashboard, além de enumerar as informações que vão ser colocadas nessa página.

É uma tarefa relativamente simples, pois uma parte dessa página ja foi feita, agora falta só adicionar mais alguns poucos elementos e melhorar o conteúdo.

**Comment by nicolessouza** [comment]
Posso começar com essa! :)
