### ISSUE TITLE
Página de listagem das ocorrências

### ISSUE THREAD

**Issue by juanbelieni** [juanbelieni/romme-net#2]
Página com a listagem das ocorrências, indo da mais recente para a mais antiga.

Pode ser uma lista de cards, ou uma tabela. É interessante testar as duas possibilidades e ver qual fica melhor.

Adicionar também um componente de paginação, para que, no futuro, ele seja usado para navegar entre as várias ocorrências que vão ser criadas.

**Comment by LucasWestfal** [comment]
Essa eu mato no peito 😎
