### ISSUE TITLE
Footer da aplicação

### ISSUE THREAD

**Issue by juanbelieni** [juanbelieni/romme-net#3]
Criar um footer no estilo da imagem abaixo, e preencher com informações genéricas.

![image](https://user-images.githubusercontent.com/29464328/134439869-58c2c308-4690-409d-9d92-4ebbbe0b5f28.png)

Utilizar a tag `footer`.

Obs.: não existe um componente de footer no bootstrap, então será necessário utilizar outros componentes mais elementares para construí-lo.

**Comment by CarlSouza** [comment]
eu tank esse

**Comment by CarlSouza** [comment]
Eu pego essa parte
