### ISSUE TITLE
Avatar na navbar

### ISSUE THREAD

**Issue by juanbelieni** [juanbelieni/romme-net#8]
Adicionar um avatar simples na navbar de tal maneira que, ao clicar, aparece a opção de fazer logout da aplicação em um dropdown.

Ela deve ser posicionada à direita do botão de "Nova ocorrência" existente hoje.

No ícone, já que nossa aplicação não terá profile pictures (ainda bem), deve ser utilizado uma letra maiúscula referente ao nome da pessoa no sistema, como acontece no Gmail. Por hora, utilizar apenas uma letra qualquer como placeholder. Exemplo:

![image](https://user-images.githubusercontent.com/29464328/134733299-a9690c26-0b16-4289-a595-990237d5226b.png)

Links úteis:
https://getbootstrap.com/docs/5.1/components/navbar/
https://getbootstrap.com/docs/5.1/components/dropdowns/
https://getbootstrap.com/docs/5.0/utilities/borders/#border-radius

**Comment by nicolessouza** [comment]
Farei essa
